#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
subsetType=$1
fontName=$2
fontType=('ttf' 'woff' 'woff2')
fontList=()
fontFile="$DIR/fonts/$fontName"
textFile=$DIR/glyphs/$subsetType/glyphs.txt
SUB=$DIR/$subsetType/$fontName
for font in $fontFile/*.ttf; do	
	fontList=(${fontList[@]} "$font")
done


if test ! -d $SUB
	then mkdir -p $DIR/$subsetType/$fontName/Subset
fi
function makeSubset(){
	if [ $subsetType != kr ]; then
		local val=$1
		mkdir -p $SUB/Subset/sub${val}
	fi
	for ext in ${fontType[*]}; do
		for p in ${fontList[*]}; do			
			filename=$(basename "$p")			
			title="${filename%.*}"
			printf "Making \e[1m\e[34m$title.$ext\e[0m..."
			output_file=$DIR/$subsetType/$fontName/Subset/$title.$ext
			if [ $ext != ttf ]; then
				flavor=$ext
			fi			
			if [ $subsetType != kr ]; then
				textFile=$DIR/glyphs/$subsetType/glyphs${val}.txt
				output_file=$DIR/$subsetType/$fontName/Subset/sub${val}/$title.$ext
			fi			
			pyftsubset "$p" --flavor=$flavor --with-zopfli --output-file="$output_file" --text-file=$textFile --layout-features='*'   --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline   --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' --passthrough-tables --drop-tables=
			if [ $? ]; then
				printf "\e[31m done!\n"
			fi
		done
	done
}

#
# bash 파일 실행 시 매개변수
#  $1 : kr || google
# $2 : 폰트이름
#
if [ $subsetType != kr ]; then
	for i in {0..119};do
		makeSubset $i
	done
else
	makeSubset
fi