#!/bin/bash
fontFile="$(cd ../../ && pwd)/fonts"
function makeSubset(){
	local val=$1
	mkdir -p $SUB/sub${val}
	for p in $fontFile/$fontName/*.ttf; do
		filename=$(basename "$p")
		title="${filename%.ttf}"		
		output_file=$DIR/Subset/sub${val}/$filename
		pyftsubset "$p" --output-file="$output_file" --text-file=$(dirname   "$DIR")/glyphs/glyphs${val}.txt --unicodes="U+2603,U+E000,U+E001" --layout-features='*' --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' --drop-tables= --passthrough-tables
		pyftsubset "$p" --flavor="woff" --with-zopfli --output-file="${output_file/ttf/woff}" --text-file=$(dirname   "$DIR")/glyphs/glyphs${val}.txt --unicodes="U+2603,U+E000,U+E001" --layout-features='*' --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' --drop-tables= --passthrough-tables
		pyftsubset "$p" --flavor="woff2" --output-file="${output_file/ttf/woff2}" --text-file=$(dirname   "$DIR")/glyphs/glyphs${val}.txt --unicodes="U+2603,U+E000,U+E001" --layout-features='*' --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' --drop-tables= --passthrough-tables
		if [ $? ]; then
			printf "done!\n"
		fi
	done
}
for i in {0..1};do
	makeSubset $i
done




#function makeSubset(){
#	for ext in ttf woff woff2; do
#		for p in $fontFile/$fontName/*.ttf; do
#			filename=$(basename "$p")
#			title="${filename%.*}"
#			printf "Making \e[1m\e[34m$title.$ext\e[0m..."
#			output_file=$DIR/Subset/$filename
#			output_file=${output_file/ttf/$ext}
#			if [ $ext != ttf ]; then
#				flavor=$ext
#			fi
#			pyftsubset "$p" --flavor=$flavor --output-file="$output_file" --text-file=$textFile --layout-features='*'   --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline   --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' --drop-tables=
#			if [ $? ]; then
#				printf "done!\n"
#			fi
#		done
#	done
#}
#makeSubset